version: "3.3"

services:

  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG" # Turn off for production
      - "--api"
      - "--accesslog" # Enable logging
      - "--accessLog.filePath=/opt/traefik/access.log"
      - "--accessLog.format=json"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"      
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=worf@klingon.me"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"
    volumes:
      - "./traefik:/opt/traefik"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      # Dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.klingon.me`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=dashboard-auth"
      - "traefik.http.routers.traefik.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=draalin:$$2y$$05$$yq78dWB6WJ0reVQG8w/lAOTr9i9371eO2vrHX9XjhC5tA6UFMA/0S"
  
  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.klingon.me`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=mytlschallenge"

  nginx:
    image: nginx:1.17
    restart: always
    logging:
      options:
        max-size: "10k"
        max-file: "4"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.klingon.me`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.nginx.middlewares=nginx-auth"
      - "traefik.http.middlewares.nginx-auth.basicauth.users=draalin:$$2y$$05$$yq78dWB6WJ0reVQG8w/lAOTr9i9371eO2vrHX9XjhC5tA6UFMA/0S"
